src/chapter7/beans/Comment.java
package chapter7.beans;


import java.sql.Date;

import javax.servlet.http.HttpServlet;

//commentidをStringに（deltecommentservlet)

public class Comment extends HttpServlet {
	private static final long serialVersionUID = 1L;

	private String id;
	private int user_id;
	private String message_id;
	private String text;
	private Date created_date;


	public String getId() {
		return id;
	}
	public void setId(String string){
		this.id = string;

	}

	public int getUserId(){
		return user_id;
	}
	public void setUserId(int user_id){
		this.user_id = user_id;
	}
	
	public String getMessageId(){
		return message_id;
	}
	
	public void setMessageId(String message_id){
		this.message_id = message_id;
	}
	
	public String getText(){
		return text;
	}
	public void setText(String text){
		this.text = text;
	}
	public Date getCreatedDate(){
		return created_date;
	}
	public void setCreatedDate(Date created_date){
		this.created_date = created_date;
		
	}
}

src/chapter7/beans/User.java
package chapter7.beans;

import java.io.Serializable;
import java.util.Date;

public class User implements Serializable {
    private static final long serialVersionUID = 1L;

    private int id;
    private String account;
    private String name;
    private String password;
    private String branch_code;
    private String department_code;
    private Date created_date;
    private Date updated_date;
    private String authority;
    
    
    public int getId() {
    	return id;
    }
    public void  setId(int id){
    	this.id = id;
    }
    	public String getAccount(){
    		return account;
    	}
    	public void setAccount(String account){
    		this.account = account;
    }
    	public String getName(){
    		return name;
    	}
    	public void setName(String name){
    		this.name = name;
    	}
    	public String getPassword(){
    		return password;
    	}
    	public void setPassword(String password){
    		this.password = password;
    	}
    	public String getBranchCode(){
    		return branch_code;
    	}
    	public void setBranchCode(String branch_code){
    		this.branch_code = branch_code;
    	}
    	public String getDepartmentCode(){
    		return department_code;
    	}
    	public void setDepartmentCode(String department_code){
    		this.department_code = department_code;   		
    	}
    	public Date getCreatedDate() {
    		return created_date;
    	}
    	public void setCreatedDate(Date created_date) {
    		this.created_date = created_date;
    	}
    	public Date getUpdatedDate() {
    		return updated_date;
    	}
    	public void setUpdatedDate(Date updated_date) {
    		this.updated_date = updated_date;
    	}
    	
    	public String getAuthority(){
    		return authority;
    	}
    	public void setAuthority(String authority){
    		this.authority = authority;
    	}
    	
    // getter/setterは省略
}

src/chapter7/controller/HomeServlet.java
package chapter7.controller;

import java.io.IOException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.commons.lang.StringUtils;

import chapter7.beans.UserComment;
import chapter7.beans.UserMessage;
import chapter7.service.CommentService;
import chapter7.service.MessageService;



@WebServlet(urlPatterns = { "/home" })
public class HomeServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;

	@Override
	protected void doGet(HttpServletRequest request,
			HttpServletResponse response) throws IOException, ServletException {


		List<UserMessage> messages = null;

		String searchCategory = request.getParameter("searchCategory");
		String startDate = getStartDate(request);
		String endDate = getEndDate(request);


		if (StringUtils.isEmpty(searchCategory) == false) {
			messages = new MessageService().select(searchCategory);
		} else {
			messages = new MessageService().getMessage();
		}

		if(StringUtils.isEmpty(startDate) == false && StringUtils.isEmpty(endDate)== false){
			messages = new MessageService().search(startDate, endDate);
//			messages = new MessageService().search(endDate);
		}else{
			messages = new MessageService().getMessage();
		}

		List<UserComment> comments = new CommentService().getComment();

		request.setAttribute("messages", messages);
		request.setAttribute("comments", comments);
		request.setAttribute("searchCategory", searchCategory);
		request.setAttribute("startDate", startDate);
		request.setAttribute("endDate", endDate);



		request.getRequestDispatcher("home.jsp").forward(request, response);
	}
	
	private static String getEndDate(HttpServletRequest req) {
		if (StringUtils.isEmpty(req.getParameter("endDate"))) {
			return LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd"));
		}
		return req.getParameter("endDate");
	}

	private static String getStartDate(HttpServletRequest req){
		if (StringUtils.isEmpty(req.getParameter("startDate"))){
			return LocalDateTime.of(2018, 07, 01, 00, 00, 0).format(DateTimeFormatter.ofPattern("yyyy-MM-dd"));
					
//					LocalDateTime.parse("2018-01-01").format(DateTimeFormatter.ofPattern("yyyy-MM-dd"));
		}
		return req.getParameter("startDate");
	}
	
	
}

src/chapter7/controller/LoginServlet.java
package chapter7.controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import chapter7.beans.User;
import chapter7.service.LoginService;

@WebServlet(urlPatterns = { "/login" })
public class LoginServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;

	@Override
	protected void doGet(HttpServletRequest request,
			HttpServletResponse response) throws IOException, ServletException {

		request.getRequestDispatcher("login.jsp").forward(request, response);
	}

	@Override
	protected void doPost(HttpServletRequest request,
			HttpServletResponse response) throws IOException, ServletException {

		String account = request.getParameter("account"); //request parameter=外からの値を取得する
		String password = request.getParameter("password"); 
//		int authority = Integer.parseInt(request.getParameter("authority"));

		
		LoginService loginService = new LoginService();
		User user = loginService.login(account, password);

		HttpSession session = request.getSession();
		if (user != null) {
//			if((authority==1)){

				session.setAttribute("loginUser", user);
				response.sendRedirect("home");
//			}else{
//				List<String> messages = new ArrayList<String>();
//				messages.add("権限がありません");
//				session.setAttribute("errorMessages", messages);
//				response.sendRedirect("login");
//			}

		} else {

			List<String> messages = new ArrayList<String>();
			messages.add("ログインに失敗しました。");
			session.setAttribute("errorMessages", messages);
			response.sendRedirect("login");

		}
	}

}

src/chapter7/controller/ManagementServlet.java
package chapter7.controller;

import java.io.IOException;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import chapter7.beans.User;
import chapter7.service.UserService;


@WebServlet(urlPatterns = { "/management" })
public class ManagementServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;

	@Override
	protected void doGet(HttpServletRequest request,
			HttpServletResponse response) throws IOException, ServletException {

	
		List<User> users = new UserService().getResisterUsers();
		request.setAttribute("users", users);
		request.getRequestDispatcher("management.jsp").forward(request, response);
	
}
	@Override
	protected void doPost(HttpServletRequest request,
			HttpServletResponse response) throws IOException, ServletException {
//		String account = request.getParameter("account");
////		  HttpSession session = request.getSession();
////	        //セッションよりログインユーザーの情報を取得
////	        User User = (User) session.getAttribute("account");
//	        //ログインユーザー情報のidを元にDBからユーザー情報取得
//	        User editUser = new UserService().getEditUser(account);
//	        request.setAttribute("editUser", editUser);
//
//	        request.getRequestDispatcher("editing.jsp").forward(request, response);
	    }
	
	
}

src/chapter7/controller/SignUpServlet.java
package chapter7.controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.commons.lang.StringUtils;

import chapter7.beans.User;
import chapter7.service.UserService;

@WebServlet(urlPatterns = { "/signup" })
public class SignUpServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;

	@Override
	protected void doGet(HttpServletRequest request,
			HttpServletResponse response) throws IOException, ServletException {

		request.getRequestDispatcher("signup.jsp").forward(request, response);
	}

	@Override
	protected void doPost(HttpServletRequest request,
			HttpServletResponse response) throws IOException, ServletException {

		List<String> messages = new ArrayList<String>();

		HttpSession session = request.getSession();
		if (isValid(request, messages) == true) {

			User user = new User();
			user.setAccount(request.getParameter("account"));
			user.setName(request.getParameter("name"));
			user.setPassword(request.getParameter("password"));
			user.setBranchCode(request.getParameter("branch_code"));
			user.setDepartmentCode(request.getParameter("department"));
			user.setAuthority(request.getParameter("authority"));

			new UserService().register(user);

			response.sendRedirect("./home");
		} else {
			session.setAttribute("errorMessages", messages);
			response.sendRedirect("signup");
		}
	}

	private boolean isValid(HttpServletRequest request, List<String> messages) {
		String account = request.getParameter("account");
		String password = request.getParameter("password");
		String name = request.getParameter("name");
		int branch_code = Integer.parseInt(request.getParameter("branch_code"));
		int department_code = Integer.parseInt(request.getParameter("department_code"));
		String passwordConfirm = request.getParameter("passwordConfirm");
		String branch = String.valueOf(branch_code);
		String department = String.valueOf(department_code);
		String authority = request.getParameter("authority");


		if (StringUtils.isEmpty(account) == true) {
			messages.add("アカウント名を入力してください");
		}
		if (StringUtils.isEmpty(password) == true) {
			messages.add("パスワードを入力してください");
		}
		if (StringUtils.isEmpty(name) == true) {
			messages.add("名前を入力してください");
		}
		if (StringUtils.isEmpty(branch) == true) {
			messages.add("支店名を入力してください");
		}
		if (StringUtils.isEmpty(department) == true) {
			messages.add("部署を入力してください");
		}
		if (account.length()<6 || account.length()>20){
			messages.add("アカウント名は6～20文字以下の英数字で設定してください");
		}
		if (!(account.matches("\\W*"))){
			messages.add("アカウント名は半角英数字で設定してください");
		}
		if (name.length() > 10){
			messages.add("名前は10文字以下で設定してください");
		}
	
		if(StringUtils.isEmpty(authority)==true){
			messages.add("ユーザーの状態を入力してください");
		}

		//		if (account.length() < 6 || 20 < account.length() ){
		//			messages.add("ログインIDは6文字以上20文字以下で設定してください");
		//
		//		}else if(!account.matches("[0-9A-Za-z]+$")){
		//			messages.add("ログインIDは半角英数字で設定してください");		
		//			}else {
		//				
		//			}


		if (!(password.equals(passwordConfirm))){
			messages.add("確認用パスワードと一致しません");
		}
		// TODO アカウントが既に利用されていないか、メールアドレスが既に登録されていないかなどの確認も必要
		if (messages.size() == 0) {
			return true;
		} else {
			return false;
		}
	}

}
//|| account.matches("[0-9A-Za-z]+$")
//		if (!account.matches("[0-9A-Za-z]+$") ){
//		messages.add("ログインIDは半角英数字で設定してください");		}

WebContent/editing.jsp
<%@page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>${loginUser.account}の設定</title>
<link href="css/style.css" rel="stylesheet" type="text/css">
</head>
<body>
	<div class="main-contents">

		<c:if test="${ not empty errorMessages }">
			<div class="errorMessages">
				<ul>
					<c:forEach items="${errorMessages}" var="message">
						<li><c:out value="${message}" />
					</c:forEach>
				</ul>
			</div>
			<c:remove var="errorMessages" scope="session" />
		</c:if>

		<form action="editing" method="post">
			<br /> <input name="id" value="${editUser.id}" id="id" type="hidden" />
			<label for="name">名前</label> <input name="name"
				value="${editUser.name}" id="name" /><br /> <label for="account">アカウント名</label>
			<input name="account" value="${editUser.account}" /><br /> <label
				for="password">パスワード</label> <input name="password" type="password"
				id="password" /> <br /> <label for="passwordConfirm">パスワード(確認用)</label>
			<input name="passwordConfirm" type="password" id="passwordConfirm" /><br />
			 <label for="branch_code">支店コード</label> <input
				name="branch_code" value="${editUser.branchCode}" id="email" /> <br />

			<label for="department">部署名</label> <input name="department_code"
				value="${editUser.departmentCode}" id="department_code" /><br /> <input
				type="submit" value="登録" /> <br /> <a href="./">戻る</a>
		</form>
		<div class="copyright">Copyright(c)Your Name</div>
	</div>
	
</body>
</html>

WebContent/home.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>ホーム画面</title>
</head>
<body>
	<div class="profile">
		<div class="name">
			<h2>
				<c:out value="${loginUser.name}" />

				さんようこそ
			</h2>
		</div>
	</div>


	<a href="newpost.jsp">新規投稿</a>
	<br />



	<form action="management" method="get">
		<input type="submit" value="登録情報の管理"> <input type="hidden"
			name="branch_code" value="${loginUser.branchCode}">
	</form>
	<br />
	<br />
	<div class="searchCategories">
		<c:if test="${ not empty errorMessages }">
			<div class="errorMessages">
				<ul>
					<c:forEach items="${errorMessages}" var="message">
						<li><c:out value="${message}" />
					</c:forEach>
				</ul>
			</div>
			<c:remove var="errorMessages" scope="session" />
		</c:if>
		<form action="home" method="get">
			カテゴリ検索（部分一致）<br /> <input type="text" name="searchCategory"
				class="searchCategory"
				value='<c:out value="${searchCategory}"></c:out>'></input> <input
				type="submit" value="検索" /> <br /> <br />

			期間指定検索(yyyy-mm-ddの形式で入力)<br /> <input type="text" name="startDate"
				class="searchDate" value='<c:out value="${startDate}"></c:out>'></input>から<input
				type="text" name="endDate" class="searchDate"
				value='<c:out value="${endDate}"></c:out>'></input>まで <br />
			<input type="submit" value="検索" /> <br /> <br />
		</form>
	</div>



	<div class="messages">
		<c:forEach items="${messages}" var="message">
			<div class="message">
				<div class="account-name">
					<font size=4><span class="account"><c:out
								value="${message.account}" /></span> <span class="name"><c:out
								value="${message.name}" /></span></font>

				</div>
				<div class="tittle">
					タイトル：
					<c:out value="${message.tittle}" />
				</div>
				<div class="category">
					カテゴリー：
					<c:out value="${message.category}" />
				</div>
				<div class="text">
					<font size=5> <c:out value="${message.text}" />
					</font>
				</div>
				<form action="deleteMessage" method="post">
					<c:if test="${loginUser.id==message.userId}">
						<input type="hidden" name="message_id" value="${message.id}">
						<input type="submit" value="投稿の削除" />

						<br />
					</c:if>
				</form>


				<div class="date">
					<fmt:formatDate value="${message.createdDate}"
						pattern="yyyy/MM/dd HH:mm:ss" />
					<br />
				</div>
			</div>

			<div class="comments">
				<c:if test="${ not empty errorMessages }">
					<div class="errorMessages">
						<ul>
							<c:forEach items="${errorMessages}" var="message">
								<li><c:out value="${message}" />
							</c:forEach>
						</ul>
					</div>
					<c:remove var="errorMessages" scope="session" />
				</c:if>
				<div class="comment">
					<form action="newComment" method="post">
						コメントする<br />

						<textarea name="text" cols="100" rows="2" class="tweet-box"></textarea>
						<c:out value="${message.id}" />
						<input type="hidden" name="message_id" value="${message.id}">
						<input type="submit" value="送信" /> <br /> <br />
					</form>
					<c:forEach items="${comments}" var="comment">

						<c:if test="${message.id==comment.messageId}">
							★
								<div class="account-name">
								<span class="account"><c:out value="${comment.account}" /></span>
								<span class="name"><c:out value="${comment.name}" /></span>
							</div>
							<div class="text">
								<c:out value="${comment.text}" />
							</div>

							<div class="date">
								<fmt:formatDate value="${comment.createdDate}"
									pattern="yyyy/MM/dd HH:mm:ss" />
								<br />
							</div>
							<form action="deleteComment" method="post">
								<c:if test="${loginUser.id==comment.userId}">
									<input type="hidden" name="comment_id" value="${comment.id}">
									<input type="submit" value="コメント削除" />
								</c:if>
							</form>
							<br />
						</c:if>
					</c:forEach>
				</div>
			</div>
			<br />
		</c:forEach>
	</div>


	<c:if test="${ not empty loginUser }">

		<a href="logout">ログアウト</a>
	</c:if>

	<br />
	<a href="login.jsp">戻る</a>
</body>
</html>

WebContent/login.jsp
<%@page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>掲示板</title>
<link href="./css/style.css" rel="stylesheet" type="text/css">
</head>
<body>
	<font size=6>掲示板</font>
	<div class="main-contents">

		<c:if test="${ not empty errorMessages }">
			<div class="errorMessages">
				<ul>
					<c:forEach items="${errorMessages}" var="message">
						<li><c:out value="${message}" />
					</c:forEach>
				</ul>
			</div>
			<c:remove var="errorMessages" scope="session" />
		</c:if>

		<form action="login" method="post">
			<br /> <label for="account">ログインID</label> <input name="account"
				value="${loginUser.account}" id="account" /> <br /> <label
				for="password">パスワード</label> <input name="password" type="password"
				id="password" /> <br /> <input type="hidden" name="authority"
				value="${loginUser.authority}"> <input type="submit"
				value="ログイン" /> <br /> <a href="signup">新規登録</a>
		</form>
		<div class="copylight">Copyright(c)YukiDeguchi</div>
	</div>
</body>
</html>

WebContent/management.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>登録情報の編集</title>
</head>
<body>
	登録情報の編集
	<br />
	<div class="users">
		<table>
			<tr>
				<td>氏名</td>
				<td>アカウント名</td>
				<td>支店</td>
				<td>部署</td>
				<td>アカウントの<br /> 復活/停止
				</td>
				<td>編集</td>
			</tr>




			<c:forEach items="${users}" var="user">
				<tr>
					<td>
						<div class="name">
							<c:out value="${user.name}" />
						</div>

					</td>
					<td><div class="account">
							<c:out value="${user.account}" />
						</div></td>
					<td><div class="branch_code">
							<c:out value="${user.branchCode}" />
						</div></td>
					<td><div class="department_code">
							<c:out value="${user.departmentCode}" />
						</div></td>
					<td><form action="managementUser" method="get">

							<div class="authority">
								<c:out value="${user.authority}" />
								<input type="hidden" name="authority" value="${user.authority}">
								<input type="hidden" name="account" value="${user.account}">
								<input type="submit" value="停止/復活" />
							</div>
						</form></td>
					<td><form action="editing" method="get">
							<input type="hidden" name="id" value="${user.id}"> <input
								type="submit" value="編集" />
						</form></td>

				</tr>

			</c:forEach>




		</table>
		<br />
	</div>
	<form action=signup method=get>
		<input type="submit" value="新規登録">
	</form>
</body>
</html>

WebContent/newpost.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<title>投稿画面</title>
</head>
<body>
	<c:if test="${ not empty loginUser }">
		<div class="profile">
			<div class="name">
				<h2>
					<c:out value="${loginUser.name}" />
				</h2>
			</div>
			<div class="account">
				<c:out value="${loginUser.account}" />
			</div>

		</div>
	</c:if>

	新規投稿
	<br />

<c:if test="${ not empty errorMessages }">
				<div class="errorMessages">
					<ul>
						<c:forEach items="${errorMessages}" var="message">
							<li><c:out value="${message}" />
						</c:forEach>
					</ul>
				</div>
				<c:remove var="errorMessages" scope="session"/>
			</c:if>

	<form action="newMessage" method="post">
		<br /> <label for="tittle">Tittle</label> <input name="tittle"
			value="${tittle}" id=tittle /> <br /> <label for="category">Category</label>
		<textarea name="category" cols="35" rows="1" id="category"></textarea>
		<br /> <br />
		<textarea name="text" cols="100" rows="5" class="tweet-box"></textarea>
		<br /> <input type="submit" value="投稿">（1000文字まで）
	</form>
	<form action="home" method="get">
	<input type="submit" value="戻る">
	</form>

</body>
</html>

WebContent/signup.jsp
<%@page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>ユーザー登録</title>
</head>

<body>
<body bgcolor="	#FFFF00">
	<font size=6>ユーザー登録画面</font>
	<div class="main-contents">
		<c:if test="${ not empty errorMessages }">
			<div class="errorMessages">
				<ul>
					<c:forEach items="${errorMessages}" var="message">
						<li><c:out value="${message}" />
					</c:forEach>
				</ul>
			</div>
			<c:remove var="errorMessages" scope="session" />
		</c:if>
		<form action="signup" method="post">
			<br /> <label for="name">名前（10字以内)</label> <br /> <input
				name="name" id="name" /><br /> <br /> <label for="account">アカウント名(半角英数字6-20字以内)</label>
			<br /> <input name="account" id="account" /> <br /> <br /> <label
				for="password">パスワード(半角文字6-20字以内)</label> <br /> <input
				name="password" type="password" id="password" /> <br /> <br /> <label
				for="passwordConfirm">パスワード(確認用)</label> <br /> <input
				name="passwordConfirm" type="password" id="passwordConfirm" /><br />
			<br /> <label for="branch_code">支店</label><br /> <input
				name="branch_code" /><br /> <br /> <label for="department_code">部署・役職</label><br />
			<input name="department_code" /><br /> <label for="autuority">ユーザーの状態</label> <br />
			<input name="authority" type="authority" id="authority" />
			<br /> <input type="submit" value="登録" /> <br /> <a href="login.jsp">戻る</a>
		</form>
		<div class="copyright">Copyright(c)Your Name</div>
	</div>
</body>
</body>

</html>